# Generated by Django 4.2.20 on 2025-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muzika_app", "0002_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="submission_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dainų kėlimo pabaiga"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="submission_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dainų kėlimo pradžia"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Žaidimo tema / pavadinimas"
            ),
        ),
    ]
