# Generated by Django 4.2.20 on 2025-04-12 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "muzika_app",
            "0003_game_submission_end_date_game_submission_start_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Dainos pavadinimas"),
                ),
                (
                    "youtube_url",
                    models.URLField(max_length=255, verbose_name="YouTube nuoroda"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Įkėlimo data"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="muzika_app.game",
                        verbose_name="Žaidimas",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_songs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Įkėlė",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daina",
                "verbose_name_plural": "Dainos",
                "ordering": ["submitted_at"],
                "unique_together": {("game", "submitted_by", "youtube_url")},
            },
        ),
    ]
