# Generated by Django 4.2.20 on 2025-04-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("muzika_app", "0004_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        choices=[(3, "3 taškai"), (2, "2 taškai"), (1, "1 taškas")],
                        verbose_name="Taškai",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="muzika_app.game",
                        verbose_name="Žaidimas",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="muzika_app.song",
                        verbose_name="Daina",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_cast",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Balsuotojas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balsas",
                "verbose_name_plural": "Balsai",
                "ordering": ["-voted_at"],
                "unique_together": {
                    ("game", "voter", "points"),
                    ("game", "voter", "song"),
                },
            },
        ),
    ]
