# Generated by Django 4.2.20 on 2025-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muzika_app", "0005_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="voting_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Balsavimo pabaiga"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="voting_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Balsavimo pradžia"
            ),
        ),
    ]
