# Generated by Django 4.2.20 on 2025-04-13 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("muzika_app", "0006_game_voting_end_date_game_voting_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winners",
            field=models.ManyToManyField(
                blank=True,
                related_name="won_games",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Laimėtojai",
            ),
        ),
    ]
