# Generated by Django 4.2.20 on 2025-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("muzika_app", "0007_game_winners"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="can_create_games",
            field=models.BooleanField(
                default=True,
                help_text="Pažymėkite, jei grupės administratoriai (arba laimėtojai) gali kurti naujus žaidimus šioje grupėje.",
                verbose_name="Leisti kurti žaidimus?",
            ),
        ),
    ]
