# Generated by Django 4.2.30 on 2026-07-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzika_app', '0008_group_can_create_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Žaidimo aprašymas'),
        ),
    ]
