# Generated by Django 4.2.30 on 2026-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzika_app', '0009_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='points',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 taškai'), (4, '4 taškai'), (3, '3 taškai'), (2, '2 taškai'), (1, '1 taškas')], verbose_name='Taškai'),
        ),
    ]
