# Generated by Django 4.2.30 on 2026-07-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muzika_app', '0010_alter_vote_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Grojaraščio pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Savininkas')),
            ],
            options={
                'verbose_name': 'Grojaraštis',
                'verbose_name_plural': 'Grojaraščiai',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='muzika_app.playlist', verbose_name='Grojaraštis')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='muzika_app.song', verbose_name='Daina')),
            ],
            options={
                'verbose_name': 'Grojaraščio daina',
                'verbose_name_plural': 'Grojaraščio dainos',
                'ordering': ['added_at'],
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
