# Generated by Django 4.2.30 on 2026-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzika_app', '0011_playlist_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Nebūtinas komentaras apie dainą (matomas tik rezultatuose).', verbose_name='Komentaras'),
        ),
    ]
